src/Entity/Links.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LinksRepository")
 */
class Links
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="text")
     */
    private $Cible;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    public function getId()
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getCible(): ?string
    {
        return $this->Cible;
    }

    public function setCible(string $Cible): self
    {
        $this->Cible = $Cible;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    public function getId()
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }
    /**
     * Returns the roles granted to the user.
     *
     * <code>
     * public function getRoles()
     * {
     *     return array('ROLE_USER');
     * }
     * </code>
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        return array('ROLE_USER');
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        // pas besoin de salt si on utilise bcrypt
        return null;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt
        ) = unserialize($serialized, ['allowed_classes' => false]);
    }
}

src/Form/AddLinkType.php
<?php

namespace App\Form;

use App\Entity\Links;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AddLinkType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Nom')
            ->add('Cible')
            ->add('Description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Links::class,
        ]);
    }
}

src/Controller/LinksController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use App\Entity\Links;
use App\Repository\LinksRepository;
use App\Form\AddLinkType;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class LinksController extends Controller
{
    /**
     * @Route("/", name="home")
     */
    public function index()
    {
        $em = $this->getDoctrine()->getManager();
        $links = $em->getRepository(Links::class)->findAll();

        return $this->render('links/index.html.twig', [
            'titre' => 'Liste des liens',
            'links' => $links,
        ]);
    }

    /**
     * @Route("/view/{id}", name="view")
     */
    public function view(Links $link)
    {

        return $this->render('links/view.html.twig', [
            'titre' => 'Visionner le lien',
            'link' => $link,
        ]);
    }

    /**
     * @Route("/add", name="add")
     */
    public function add(Request $request)
    {

        $link = new Links();
        $form = $this->createForm(AddLinkType::class, $link);

        $form->handleRequest($request);
        
        if($form->isSubmitted() && $form->isValid()){

            $em = $this->getDoctrine()->getManager();
            $em->persist($link);
            $em->flush();
            return $this->redirectToRoute('home');
        }

        return $this->render('links/add.html.twig', [
            'form' => $form->createView(),
            'titre' => "Ajoût d'un lien"
        ]);
    }

    /**
    * @Route("/edit/{id}", name="edit")
    */
    public function edit(Links $link, Request $request)
    {

        $form = $this->createForm(AddLinkType::class, $link);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $em = $this->getDoctrine()->getManager();
            $em->persist($link);
            $em->flush();
            return $this->redirectToRoute('home');
        }

        return $this->render('links/add.html.twig', [
            'form' => $form->createView(),
            'titre' => 'Modification du lien'
        ]);
    }
    
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>SB Admin 2 - Bootstrap Admin Theme</title>
        <base href="http://www.florentm.poec/cloverfield/public/" />
        
        <!-- Bootstrap Core CSS -->
        <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

        <!-- MetisMenu CSS -->
        <link href="vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="dist/css/sb-admin-2.css" rel="stylesheet">

        <!-- Morris Charts CSS -->
        <!--
        <link href="vendor/morrisjs/morris.css" rel="stylesheet">
        -->
        <!-- Custom Fonts -->
        <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        
    </head>
    <body>
        <div id="wrapper">
            {% block body %}{% endblock %}

            <!-- jQuery -->
            <script src="vendor/jquery/jquery.min.js"></script>

            <!-- Bootstrap Core JavaScript -->
            <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

            <!-- Metis Menu Plugin JavaScript -->
            <script src="vendor/metisMenu/metisMenu.min.js"></script>

            <!-- Morris Charts JavaScript -->
            <!-- A activer pour charts
            <script src="vendor/raphael/raphael.min.js"></script>
            <script src="vendor/morrisjs/morris.min.js"></script>
            <script src="data/morris-data.js"></script>
            -->
            <!-- Custom Theme JavaScript -->
            <script src="dist/js/sb-admin-2.js"></script>
        </div>
    </body>
</html>

templates/body.footer.inc.html.twig
</div>

templates/body.header.inc.html.twig
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">{{ titre }}</h1>
        </div>
    </div>
    <div class="row">

templates/links/add.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'navigation.inc.html.twig' %}
    {% include 'body.header.inc.html.twig' %}

<div class="col-lg-10 col-md-10">
    <div class="panel panel-green">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-3">
                    <i class="fa fa-link"></i>
                </div>
                <div class="col-xs-9 text-right">
{{ titre }}
                </div>
            </div>
        </div>
        
        <div class="panel-body">


            <div class="row">
                <div class="col-lg-12">

{{ form_start(form) }}
{{ form_errors(form) }}
{{ form_rest(form) }}
<button type="submit" class="btn btn-primary">Save</button>
{{ form_end(form) }}
                
                
                </div>
            </div>
        </div>
    </div>
</div>

    {% include 'body.footer.inc.html.twig' %}
{% endblock %}

templates/links/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'navigation.inc.html.twig' %}
    {% include 'body.header.inc.html.twig' %}

    {% for link in links %}
<div class="col-lg-6 col-md-6">
    <div class="panel panel-green">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-9">
{{ link.nom }}
                </div>
                <div class="col-xs-3 text-right">
{% include 'modify.inc.html.twig' %}
                </div>
            </div>
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-12">
                    <a href="" class="text-success">tag1</a> / <a href="" class="text-success">tag2</a> / <a href="" class="text-success">tag3</a>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
{{ link.description|truncate(200) }}
                </div>
            </div>
        </div>

        <div class="panel-footer">
            <span class="pull-left">
                <i class="fa fa-arrow-circle-right"></i> <a class="text-success" target="_blank" href="{{ link.cible }}">{{ link.cible }}</a>
            </span>
            <div class="clearfix"></div>
        </div>
        
    </div>
</div>
    {% endfor %}
    
    {% include 'body.footer.inc.html.twig' %}
{% endblock %}

templates/links/view.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'navigation.inc.html.twig' %}
    {% include 'body.header.inc.html.twig' %}

<div class="col-lg-10 col-md-10">
    <div class="panel panel-green">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-9">
{{ link.nom }}
                </div>
                <div class="col-xs-3 text-right">
{% include 'modify.inc.html.twig' %}
                </div>

            </div>
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-12">
                    <a href="" class="text-success">tag1</a> / <a href="" class="text-success">tag2</a> / <a href="" class="text-success">tag3</a>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
{{ link.description }}
                </div>
            </div>
        </div>

        <div class="panel-footer">
            <span class="pull-left">
                <i class="fa fa-arrow-circle-right"></i> <a class="text-success" target="_blank" href="{{ link.cible }}">{{ link.cible }}</a>
            </span>
            <div class="clearfix"></div>
        </div>
        
    </div>
</div>
    
    {% include 'body.footer.inc.html.twig' %}
{% endblock %}

templates/modify.inc.html.twig
<div class="btn-group">
    <button type="button" class="btn btn-success btn-sm dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-gear"></i> <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li><a href="{{ path('view', {id : link.id}) }}"><i class="fa fa-book fa-fw"></i> Consulter</a>
        </li>
        <li><a href="{{ path('edit', {id : link.id}) }}"><i class="fa fa-edit fa-fw"></i> Modifier</a>
        </li>
        <li><a href="#"><i class="fa fa-times fa-fw"></i> Supprimer</a>
        </li>
    </ul>
</div>

templates/navigation.inc.html.twig
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{ path('home') }}">Cloverfield</a>
    </div>

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <a href="#"><i class="fa fa-link fa-fw"></i> Gérer les liens<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="{{ path('home') }}"> Lister les liens</a>
                        </li>
                        <li>
                            <a href="{{ path('add') }}"> Ajoûter un lien</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="fa fa-users fa-fw"></i> Gérer les utilisateurs</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-sign-out fa-fw"></i> Me déconnecter</a>
                </li>
            </ul>
        </div>
    </div>
</nav>